[package]
name = "rdl"
version = "0.1.0"
authors = ["Axel Boldt-Christmas <xmas1915@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdl-lib = { path = "./rdl-lib" }